//@ sourceMappingURL=explosion.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  ig.module('game.entities.explosion').requires('impact.entity').defines(function() {
    return _this.EntityExplosion = ig.Entity.extend({
      type: ig.Entity.TYPE.NONE,
      checkAgainst: ig.Entity.TYPE.NONE,
      collides: ig.Entity.COLLIDES.NEVER,
      size: {
        x: 16,
        y: 16
      },
      animSheet: new ig.AnimationSheet('media/explosion.png', 16, 16),
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        this.addAnim('idle', .1, [0, 1, 2, 3]);
        this.dieTimer = new ig.Timer(.4);
        return ig.game.explosionSound.play();
      },
      update: function() {
        this.parent();
        if (this.dieTimer.delta() > 0) {
          return this.kill();
        }
      }
    });
  });

}).call(this);
