//@ sourceMappingURL=star.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  ig.module('game.entities.star').requires('impact.entity').defines(function() {
    return _this.EntityStar = ig.Entity.extend({
      type: ig.Entity.TYPE.NONE,
      checkAgainst: ig.Entity.TYPE.NONE,
      collides: ig.Entity.COLLIDES.NEVER,
      size: {
        x: 3,
        y: 3
      },
      animSheet: new ig.AnimationSheet('media/stars.png', 3, 3),
      init: function(x, y, settings) {
        var image;
        x = ig.system.width * Math.random();
        y = ig.system.height * Math.random();
        this.parent(x, y);
        image = [0, 0, 0, 0, 2, 1, 1, 1, 1, 3].random();
        this.addAnim('idle', 1, [image]);
        return this.currentAnim.alpha = Math.random().limit(.7, 1);
      }
    });
  });

}).call(this);
