//@ sourceMappingURL=main.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  ig.module('game.main').requires('impact.game', 'game.entities.planet', 'game.entities.star', 'impact.debug.debug').defines(function() {
    _this.MyGame = ig.Game.extend({
      playerFont: new ig.Font("media/player_font.png"),
      enemyFont: new ig.Font("media/enemy_font.png"),
      planets: [],
      init: function() {
        var num, _i, _j, _k, _l, _m, _results;
        ig.input.bind(ig.KEY.MOUSE1, 'click');
        for (num = _i = 1; _i <= 150; num = ++_i) {
          this.spawnEntity(EntityStar);
        }
        for (num = _j = 1; _j <= 3; num = ++_j) {
          this.spawnEntity(EntityPlanet, {
            enemy: false,
            ship: "destroyer"
          });
        }
        for (num = _k = 1; _k <= 3; num = ++_k) {
          this.spawnEntity(EntityPlanet, {
            enemy: false,
            ship: "fighter"
          });
        }
        for (num = _l = 1; _l <= 3; num = ++_l) {
          this.spawnEntity(EntityPlanet, {
            enemy: true,
            ship: "destroyer"
          });
        }
        _results = [];
        for (num = _m = 1; _m <= 3; num = ++_m) {
          _results.push(this.spawnEntity(EntityPlanet, {
            enemy: true,
            ship: "fighter"
          }));
        }
        return _results;
      },
      update: function() {
        return this.parent();
      },
      draw: function() {
        var enemyPlanets, enemyShips, playerPlanets, playerShips;
        this.parent();
        playerPlanets = this.getEntitiesByType(EntityPlanet).filter(function(planet) {
          return !planet.enemy;
        });
        playerShips = this.getEntitiesByType(EntityShip).filter(function(ship) {
          return !ship.ki;
        });
        enemyPlanets = this.getEntitiesByType(EntityPlanet).filter(function(planet) {
          return planet.enemy;
        });
        enemyShips = this.getEntitiesByType(EntityShip).filter(function(ship) {
          return ship.ki;
        });
        this.playerFont.draw(playerPlanets.length, 2, 2, ig.Font.ALIGN.LEFT);
        this.enemyFont.draw(enemyPlanets.length, ig.system.width - 2, 2, ig.Font.ALIGN.RIGHT);
        if (playerPlanets.length === 0) {
          this.write("You've been annihilated.", this.enemyFont);
        }
        if (enemyPlanets.length === 0) {
          this.write("You've won the war!", this.playerFont);
        }
        if (playerShips.length === 0 && enemyShips.length === 0) {
          if (playerPlanets.length > enemyPlanets.length) {
            this.write("You've won the war!", this.playerFont);
          }
          if (playerPlanets.length < enemyPlanets.length) {
            this.write("You've lost the war.", this.enemyFont);
          }
          if (playerPlanets.length === enemyPlanets.length) {
            return this.write("The war is over. Tie.", this.playerFont);
          }
        }
      },
      write: function(text, font) {
        font.draw(text, ig.system.width / 2, ig.system.height / 2 - font.height, ig.Font.ALIGN.CENTER);
        font.draw("Click to play again.", ig.system.width / 2, ig.system.height / 2, ig.Font.ALIGN.CENTER);
        if (ig.input.pressed('click')) {
          return ig.system.setGame(MyGame);
        }
      }
    });
    return ig.main('#canvas', MyGame, 60, 400, 300, 2);
  });

}).call(this);
