//@ sourceMappingURL=main.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  ig.module('game.main').requires('impact.game', 'game.entities.planet', 'impact.debug.debug').defines(function() {
    _this.MyGame = ig.Game.extend({
      playerFont: new ig.Font("media/player_font.png"),
      enemyFont: new ig.Font("media/enemy_font.png"),
      init: function() {
        var num, _i, _j, _results;
        ig.input.bind(ig.KEY.MOUSE1, 'click');
        for (num = _i = 1; _i <= 6; num = ++_i) {
          this.spawnEntity(EntityPlanet, {
            enemy: false
          });
        }
        _results = [];
        for (num = _j = 1; _j <= 6; num = ++_j) {
          _results.push(this.spawnEntity(EntityPlanet, {
            enemy: true
          }));
        }
        return _results;
      },
      update: function() {
        return this.parent();
      },
      draw: function() {
        var enemyPlanets, playerPlanets;
        this.parent();
        playerPlanets = this.getEntitiesByType(EntityPlanet).filter(function(planet) {
          return !planet.enemy;
        });
        enemyPlanets = this.getEntitiesByType(EntityPlanet).filter(function(planet) {
          return planet.enemy;
        });
        this.playerFont.draw(playerPlanets.length, 2, 2, ig.Font.ALIGN.LEFT);
        return this.enemyFont.draw(enemyPlanets.length, ig.system.width - 2, 2, ig.Font.ALIGN.RIGHT);
      }
    });
    return ig.main('#canvas', MyGame, 60, 400, 300, 2);
  });

}).call(this);
